# Generated by Django 4.0.6 on 2022-07-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.IntegerField(verbose_name='Номер повторения')),
                ('question', models.IntegerField(verbose_name='Номер вопроса')),
                ('text', models.CharField(default='Вопрос', max_length=500, verbose_name='Текст вопроса')),
                ('data', models.TextField(verbose_name='Показатели фотоплетизмограмма')),
                ('data2', models.TextField(verbose_name='Показатели пьезоплетизмограмма')),
                ('class_label', models.IntegerField(verbose_name='Класс стресса')),
                ('state', models.IntegerField(choices=[(0, 'Новый'), (1, 'Ручное'), (2, 'Автоматическое')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Номер теста')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.person', verbose_name='Испытуемый')),
            ],
        ),
    ]
