# Generated by Django 4.0.6 on 2022-07-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.person', verbose_name='Испытуемый'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.IntegerField(default=1, verbose_name='Номер теста'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
