# Generated by Django 4.0.6 on 2022-07-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_person_question_test_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='data',
            new_name='data1',
        ),
    ]
