# Generated by Django 4.0.6 on 2022-07-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='class_label',
            field=models.IntegerField(blank=True, null=True, verbose_name='Класс стресса'),
        ),
    ]
